import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { QueryProvider } from '@/providers/QueryProvider'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const hasToken = (await cookies()).has('token')

  if (hasToken) {
    redirect('/documents')
  }

  return (
    <html lang="en">
      <body className={`font-sans !font-poppins  antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
