import type { Metadata } from 'next'
import '../globals.css'
import { QueryProvider } from '@/providers/QueryProvider'
import { Header } from '@/components/Header'
import { Toaster } from 'sonner'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const hasToken = (await cookies()).has('token')

  if (!hasToken) {
    redirect('/')
  }

  return (
    <html lang="en">
      <body className="font-poppins antialiased">
        <Header />
        <QueryProvider>
          {children}
          <Toaster position="top-right" richColors />
        </QueryProvider>
        <Footer />
      </body>
    </html>
  )
}
